### ISSUE TITLE
Garmin今天晚上突然同步不了了

### ISSUE THREAD

**Issue by WangShanpeng** [XiaoSiHwang/sport-sync#6]
报错如下，请问是佳明服务器的接口变了吗，能否修复？非常感谢

```
Traceback (most recent call last):
  File "scripts/garmin/garmin_sync.py", line 152, in <module>
    loop.run_until_***plete(asyncio.gather(*get_all_activity_list_tasks))
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_***plete
    return future.result()
  File "/home/runner/work/Garmin-Sync/Garmin-Sync/scripts/garmin/garmin_connect.py", line 235, in get_all_activity_list
    respone = await self.get_activitys(100, start)
  File "/home/runner/work/Garmin-Sync/Garmin-Sync/scripts/garmin/garmin_connect.py", line 143, in get_activitys
    return await self.featch_get_request_data(url)
  File "/home/runner/work/Garmin-Sync/Garmin-Sync/scripts/garmin/garmin_connect.py", line 157, in featch_get_request_data
    raise err
  File "/home/runner/work/Garmin-Sync/Garmin-Sync/scripts/garmin/garmin_connect.py", line 154, in featch_get_request_data
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Redirect response '[30](https://github.com/WangShanpeng/Garmin-Sync/actions/runs/6027045914/job/16351343889#step:7:31)2 Moved Temporarily' for url '[https://connect.garmin.***/proxy/activitylist-service/activities/search/activities?start=0&limit=100](https://connect.garmin.%2A%2A%2A/proxy/activitylist-service/activities/search/activities?start=0&limit=100)'
Redirect location: '[https://static.garmincdn.***/connectstatus/connect-maintenance-500.html](https://static.garmincdn.%2A%2A%2A/connectstatus/connect-maintenance-500.html)'
For more information check: [https://httpstatuses.***/302](https://httpstatuses.%2A%2A%2A/302)
Error: Process ***pleted with exit code 1.
```

**Comment by WangShanpeng** [comment]
[Github Actions 链接点这里](https://github.com/WangShanpeng/Garmin-Sync/actions/runs/6026973563/job/16351170335)

**Comment by XiaoSiHwang** [comment]
您好Sport Sync已不再维护，如需使用可以使用[DailySync佳明数据同步服务](https://dailysync.vyzt.dev/)
